src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * Article constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage(string $image)
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('image', FileType::class, [
                'label' => 'Illustration',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '500k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => "Le format de l'image n'est pas supporté",
                    ])
                ],
            ])
            ->add('name')
            ->add('firstname')
            ->add('email')
            ->add('city')
            ->add('status')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Service\FilesServices;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class ArticleController extends AbstractController
{
    /** @var FilesServices */
    private $filesServices;

    /**
     * AddMapHistoryController constructor.
     * @param FilesServices $filesServices
     */
    public function __construct(FilesServices $filesServices)
    {
        $this->filesServices = $filesServices;
    }

    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findBy(['status' => true]),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $image = $form->get('image')->getData();
            $fileName = $this->filesServices->uploadFile($image);
            $article->setImage($fileName);

            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $currentDate = new \DateTime();
            $article->setUpdatedAt($currentDate);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">

    <div class="create">
        <button class="btn btn-danger">Delete</button>
    </div>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col-12 col-lg-4">
            {{ form_label(form.title) }}
            {{ form_widget(form.title, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6">
            {{ form_label(form.description) }}
            {{ form_widget(form.description, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    {% if image is defined %}
        <div class="illustration">
            <img src="{{ asset('uploads/articles/') ~ image }}" alt="" class="img-fluid">
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12 col-lg-4">
            {{ form_label(form.image) }}
            {{ form_widget(form.image, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-4">
            {{ form_label(form.name) }}
            {{ form_widget(form.name, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="col-12 col-lg-4">
            {{ form_label(form.firstname) }}
            {{ form_widget(form.firstname, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-4">
            {{ form_label(form.email) }}
            {{ form_widget(form.email, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="col-12 col-lg-4">
            {{ form_label(form.city) }}
            {{ form_widget(form.city, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-4">
            {{ form_label(form.status) }}
            {{ form_widget(form.status) }}
        </div>
    </div>

    <div class="create">
        <button class="btn btn-info">{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un article{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center text-uppercase">Modifier un article</h1>

        {{ include('article/_form.html.twig', {'image': article.image}) }}

        <div class="create">
            <a class="btn btn-info" href="{{ path('article_index') }}">Revenir à la liste</a>
        </div>

        {{ include('article/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Articles{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center text-uppercase">Liste des Articles</h1>
        <div class="create">
            <a class="btn btn-info" href="{{ path('article_new') }}">Ecrire un Article</a>
        </div>

        <div class="row list justify-content-around">
            {% for article in articles %}
                <div class="col-12 col-lg-3 single">
                    <h3 class="text-center">{{ article.title }}</h3>
                    <p class="date">Mis en ligne le {{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</p>
                    <p class="date">Mis à Jour le {{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s') : '' }}</p>
                    <div class="illustration">
                        <img src="{{ asset('uploads/articles/') ~ article.image }}" alt="" class="img-fluid">
                    </div>
                    <div class="texte">{{ article.description|nl2br }}</div>
                    <div class="create">
                        <a class="btn btn-success" href="{{ path('article_show', {'id': article.id}) }}">Lire l'article</a>
                    </div>
                </div>
            {% else %}
                <p class="text-center">Il n'y a pas encore d'articles sur ce site</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecrire un article{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center text-uppercase">Ecrire un article</h1>

        {{ include('article/_form.html.twig') }}

        <div class="create">
            <a class="btn btn-info" href="{{ path('article_index') }}">Revenir à la liste</a>
        </div>
    </div>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center text-uppercase">{{ article.title }}</h1>
        <div class="create">
            <a class="btn btn-success" href="{{ path('article_index') }}">Revenir à la liste</a>
        </div>
        <div class="create">
            <a class="btn btn-info" href="{{ path('article_edit', {'id': article.id}) }}">Mettre à jour l'Article</a>
        </div>

        <div class="single">
            <p class="date">Mis en ligne le {{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</p>
            <p class="date">Mis à Jour le {{ article.updatedAt ? article.updatedAt|date('Y-m-d H:i:s') : '' }}</p>
            <h3 class="text-center">{{ article.title }} à {{ article.city }}</h3>
            <p class="author">Par {{ article.firstname }} {{ article.name }}</p>
            <div class="texte">{{ article.description|nl2br }}</div>
            <div class="illustration">
                <img src="{{ asset('uploads/articles/') ~ article.image }}" alt="" class="img-fluid">
            </div>
        </div>
    </div>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Liste des Articles!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link href="{{ asset('css/style.css') }}" rel="stylesheet" />
        {% endblock %}

        {% block javascripts %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>